export const COMPANIES_LOADING_START = "COMPANIES_LOADING_START";
export const COMPANIES_LOADING_STOP = "COMPANIES_LOADING_STOP";
  
export const RETRIEVE_COMPANIES = "RETRIEVE_COMPANIES"; 
export const DELETE_COMPANY = "DELETE_COMPANY"; 
 
